require:
  - rubocop
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
  
Metrics/ClassLength:
  Exclude: 
    - app/models/event.rb

Layout/IndentationWidth:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Style/AsciiComments:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
