name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.13
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://test:password@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          npm ci

      - name: Run tests
        run:
          bin/rails test
